const CHALLENGE_BADGES = [
  {
    id: "first_step",
    title: "첫 발걸음",
    desc: "첫 공부 기록 남기기",
    icon: "icon-play",
    check: (ctx) => ctx.sessionCount >= 1,
  },
  {
    id: "warm_up",
    title: "워밍업",
    desc: "누적 공부 30분",
    icon: "icon-clock",
    check: (ctx) => ctx.totalMinutes >= 30,
  },
  {
    id: "five_hours",
    title: "옆자리 지킴이",
    desc: "누적 공부 5시간",
    icon: "icon-target",
    check: (ctx) => ctx.totalMinutes >= 300,
  },
  {
    id: "ten_hours",
    title: "집중의 달인",
    desc: "누적 공부 10시간",
    icon: "icon-star",
    check: (ctx) => ctx.totalMinutes >= 600,
  },
  {
    id: "streak_3",
    title: "3일 연속",
    desc: "연속 학습 3일",
    icon: "icon-flame",
    check: (ctx) => ctx.streak >= 3,
  },
  {
    id: "streak_7",
    title: "7일 연속",
    desc: "연속 학습 7일",
    icon: "icon-flame",
    check: (ctx) => ctx.streak >= 7,
  },
  {
    id: "goal_today",
    title: "오늘의 목표",
    desc: "일일 목표 달성",
    icon: "icon-check",
    check: (ctx) => ctx.todayMinutes >= ctx.dailyGoal,
  },
  {
    id: "heart_100",
    title: "마음 열기",
    desc: "호감도 100",
    icon: "icon-heart",
    check: (ctx) => ctx.affection >= 100,
  },
  {
    id: "heart_500",
    title: "썸의 기류",
    desc: "호감도 500",
    icon: "icon-heart",
    check: (ctx) => ctx.affection >= 500,
  },
  {
    id: "prologue",
    title: "재회",
    desc: "프롤로그 완료",
    icon: "icon-book",
    check: (ctx) => ctx.storyCompleted.includes("prologue"),
  },
  {
    id: "memory",
    title: "기억의 조각",
    desc: "사건 1 완료",
    icon: "icon-gift",
    check: (ctx) => ctx.storyCompleted.includes("event1"),
  },
  {
    id: "finale",
    title: "분기점",
    desc: "사건 5 완료",
    icon: "icon-skip",
    check: (ctx) => ctx.storyCompleted.includes("event5"),
  },
  {
    id: "happy_end",
    title: "약속",
    desc: "해피 엔딩",
    icon: "icon-star",
    check: (ctx) => ctx.ending === "happy",
  },
  {
    id: "night_owl",
    title: "올빼미",
    desc: "밤 10시 이후 공부",
    icon: "icon-moon",
    check: (ctx) => ctx.hasLateNightStudy,
  },
  {
    id: "early_bird",
    title: "아침형",
    desc: "아침 7시 이전 공부",
    icon: "icon-sun",
    check: (ctx) => ctx.hasEarlyMorningStudy,
  },
];
